import { Course, ExploreCourse, User, InstructorCourse, AdminUser, InstructorRequest } from './types';

export const currentUser: User = {
  id: 'user-1',
  name: 'Darlene',
  email: 'darleneatuncar@gmail.com',
  role: 'student',
  avatarUrl: null,
};

export const myCourses: Course[] = [
  {
    id: 'course-1',
    title: 'Desarrollo Web Full Stack',
    description: 'Aprende a crear aplicaciones web completas con HTML, CSS, JavaScript, React y Node.js.',
    instructor: 'Carlos Mendoza',
    instructorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=600&auto=format&fit=crop&q=80',
    progressPercent: 68,
    totalLessons: 25,
    completedLessons: 17,
    lastLesson: 'React y Componentes',
    status: 'in_progress',
    category: 'Tecnología',
    enrolledCount: 142,
    totalModules: 3,
  },
  {
    id: 'course-2',
    title: 'Python para Ciencia de Datos',
    description: 'Domina Python, Pandas, NumPy y Matplotlib para analizar datos.',
    instructor: 'Ana García',
    instructorAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=600&auto=format&fit=crop&q=80',
    progressPercent: 45,
    totalLessons: 20,
    completedLessons: 9,
    lastLesson: 'Análisis de Datos con Pandas',
    status: 'in_progress',
    category: 'Tecnología',
    enrolledCount: 98,
    totalModules: 2,
  },
  {
    id: 'course-3',
    title: 'Diseño UX/UI Profesional',
    description: 'Conviértete en diseñador de interfaces profesionales con Figma.',
    instructor: 'Roberto Sánchez',
    instructorAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=600&auto=format&fit=crop&q=80',
    progressPercent: 100,
    totalLessons: 18,
    completedLessons: 18,
    lastLesson: null,
    status: 'completed',
    completedAt: '15 de Septiembre, 2026',
    category: 'Diseño',
    enrolledCount: 76,
    totalModules: 2,
  },
  {
    id: 'course-4',
    title: 'Marketing Digital Integral',
    description: 'Estrategias de SEO, redes sociales, email marketing y analítica.',
    instructor: 'María López',
    instructorAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&auto=format&fit=crop&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&auto=format&fit=crop&q=80',
    progressPercent: 100,
    totalLessons: 15,
    completedLessons: 15,
    lastLesson: null,
    status: 'completed',
    completedAt: '10 de Septiembre, 2026',
    category: 'Negocios',
    enrolledCount: 64,
    totalModules: 2,
  },
];

export const exploreCourses: ExploreCourse[] = [
  {
    id: 'exp-1',
    title: 'Productividad y Gestión del Tiempo',
    description: 'Técnicas probadas para gestionar tu tiempo y alcanzar tus metas.',
    instructor: 'Roberto Sánchez',
    bannerUrl: 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=600&auto=format&fit=crop&q=80',
    category: 'Desarrollo Personal',
    totalModules: 4,
    enrolledCount: 210,
    isEnrolled: false,
  },
  {
    id: 'exp-2',
    title: 'Bases de Datos y SQL',
    description: 'Diseña, crea y consulta bases de datos relacionales con SQL.',
    instructor: 'Carlos Mendoza',
    bannerUrl: 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=600&auto=format&fit=crop&q=80',
    category: 'Tecnología',
    totalModules: 3,
    enrolledCount: 87,
    isEnrolled: false,
  },
  {
    id: 'exp-3',
    title: 'Finanzas Personales',
    description: 'Aprende a administrar tu dinero, ahorrar e invertir.',
    instructor: 'Ana García',
    bannerUrl: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=600&auto=format&fit=crop&q=80',
    category: 'Negocios',
    totalModules: 3,
    enrolledCount: 156,
    isEnrolled: false,
  },
];

// ==================== INSTRUCTOR DATA ====================

export const instructorUser: User = {
  id: 'inst-1',
  name: 'Carlos Mendoza',
  email: 'carlos@educore.com',
  role: 'instructor',
  avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
};

export const instructorCourses: InstructorCourse[] = [
  {
    id: 'ic-1',
    title: 'Desarrollo Web Full Stack',
    description: 'Aprende a crear aplicaciones web completas con HTML, CSS, JavaScript, React y Node.js.',
    category: 'Tecnología',
    level: 'Intermedio',
    bannerUrl: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=600&auto=format&fit=crop&q=80',
    status: 'published',
    totalModules: 3,
    totalLessons: 12,
    enrolledCount: 142,
    updatedAt: '18 de Septiembre, 2026',
    modules: [
      {
        id: 'mod-1',
        title: 'Fundamentos de HTML y CSS',
        description: 'Aprende los cimientos del desarrollo web.',
        order: 1,
        lessons: [
          { id: 'l-1', title: 'Introducción al desarrollo web', type: 'video', duration: '15 min', order: 1 },
          { id: 'l-2', title: 'HTML semántico', type: 'text', order: 2 },
          { id: 'l-3', title: 'CSS Moderno', type: 'video', duration: '25 min', order: 3 },
          { id: 'l-4', title: 'Guía de estilos CSS', type: 'pdf', order: 4 },
        ],
      },
      {
        id: 'mod-2',
        title: 'JavaScript Moderno',
        description: 'Domina ES6+, async/await y programación funcional.',
        order: 2,
        lessons: [
          { id: 'l-5', title: 'Variables y tipos de datos', type: 'video', duration: '20 min', order: 1 },
          { id: 'l-6', title: 'Funciones y scope', type: 'text', order: 2 },
          { id: 'l-7', title: 'Async/Await', type: 'video', duration: '30 min', order: 3 },
        ],
      },
      {
        id: 'mod-3',
        title: 'React y Componentes',
        description: 'Construye interfaces modernas con React.',
        order: 3,
        lessons: [
          { id: 'l-8', title: 'Introducción a React', type: 'video', duration: '20 min', order: 1 },
          { id: 'l-9', title: 'Props y Estado', type: 'text', order: 2 },
          { id: 'l-10', title: 'Hooks principales', type: 'video', duration: '35 min', order: 3 },
          { id: 'l-11', title: 'Proyecto práctico', type: 'link', order: 4 },
          { id: 'l-12', title: 'Evaluación del módulo', type: 'pdf', order: 5 },
        ],
      },
    ],
  },
  {
    id: 'ic-2',
    title: 'Bases de Datos y SQL',
    description: 'Diseña, crea y consulta bases de datos relacionales con SQL.',
    category: 'Tecnología',
    level: 'Principiante',
    bannerUrl: 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=600&auto=format&fit=crop&q=80',
    status: 'published',
    totalModules: 2,
    totalLessons: 8,
    enrolledCount: 87,
    updatedAt: '15 de Septiembre, 2026',
    modules: [
      {
        id: 'mod-sql-1',
        title: 'Fundamentos de SQL',
        description: 'Aprende a crear y consultar bases de datos.',
        order: 1,
        lessons: [
          { id: 'l-sql-1', title: '¿Qué es una base de datos?', type: 'video', duration: '12 min', order: 1 },
          { id: 'l-sql-2', title: 'Tablas y relaciones', type: 'text', order: 2 },
          { id: 'l-sql-3', title: 'Consultas SELECT', type: 'video', duration: '22 min', order: 3 },
        ],
      },
      {
        id: 'mod-sql-2',
        title: 'Consultas Avanzadas',
        description: 'Domina JOINs, subconsultas y agregaciones.',
        order: 2,
        lessons: [
          { id: 'l-sql-4', title: 'JOINs en SQL', type: 'video', duration: '28 min', order: 1 },
          { id: 'l-sql-5', title: 'Subconsultas', type: 'text', order: 2 },
          { id: 'l-sql-6', title: 'Funciones de agregación', type: 'video', duration: '18 min', order: 3 },
          { id: 'l-sql-7', title: 'Optimización de consultas', type: 'pdf', order: 4 },
          { id: 'l-sql-8', title: 'Práctica guiada', type: 'link', order: 5 },
        ],
      },
    ],
  },
  {
    id: 'ic-3',
    title: 'Introducción a Python',
    description: 'Primeros pasos con Python: variables, bucles, funciones y más.',
    category: 'Tecnología',
    level: 'Principiante',
    bannerUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=600&auto=format&fit=crop&q=80',
    status: 'draft',
    totalModules: 1,
    totalLessons: 4,
    enrolledCount: 0,
    updatedAt: '20 de Septiembre, 2026',
    modules: [
      {
        id: 'mod-py-1',
        title: 'Primeros pasos con Python',
        description: 'Instalación, sintaxis básica y primer programa.',
        order: 1,
        lessons: [
          { id: 'l-py-1', title: '¿Por qué aprender Python?', type: 'video', duration: '10 min', order: 1 },
          { id: 'l-py-2', title: 'Instalación y configuración', type: 'text', order: 2 },
          { id: 'l-py-3', title: 'Tu primer programa', type: 'video', duration: '15 min', order: 3 },
          { id: 'l-py-4', title: 'Ejercicios iniciales', type: 'pdf', order: 4 },
        ],
      },
    ],
  },
  {
    id: 'ic-4',
    title: 'Diseño UX/UI con Figma',
    description: 'Aprende a diseñar interfaces profesionales usando Figma.',
    category: 'Diseño',
    level: 'Intermedio',
    bannerUrl: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=600&auto=format&fit=crop&q=80',
    status: 'pending_review',
    totalModules: 2,
    totalLessons: 6,
    enrolledCount: 0,
    updatedAt: '19 de Septiembre, 2026',
    modules: [
      {
        id: 'mod-fig-1',
        title: 'Fundamentos de Diseño UX',
        description: 'Principios de experiencia de usuario.',
        order: 1,
        lessons: [
          { id: 'l-fig-1', title: '¿Qué es UX?', type: 'video', duration: '14 min', order: 1 },
          { id: 'l-fig-2', title: 'Research de usuarios', type: 'text', order: 2 },
        ],
      },
      {
        id: 'mod-fig-2',
        title: 'Diseño Visual con Figma',
        description: 'Crea prototipos interactivos.',
        order: 2,
        lessons: [
          { id: 'l-fig-3', title: 'Interfaz de Figma', type: 'video', duration: '20 min', order: 1 },
          { id: 'l-fig-4', title: 'Componentes y Auto Layout', type: 'text', order: 2 },
          { id: 'l-fig-5', title: 'Prototipado', type: 'video', duration: '25 min', order: 3 },
          { id: 'l-fig-6', title: 'Recursos descargables', type: 'pdf', order: 4 },
        ],
      },
    ],
  },
];

// ==================== ADMIN MOCK DATA ====================

export const adminUser: AdminUser = {
  id: 'admin-1',
  name: 'Carlos Mendoza',
  email: 'admin@educore.com',
  role: 'admin',
  status: 'active',
  registeredAt: '2024-01-15',
  avatarUrl: null,
};

export const adminUsers: AdminUser[] = [
  adminUser,
  {
    id: 'user-2',
    name: 'Darlene Blackwell',
    email: 'darlene@ejemplo.com',
    role: 'student',
    status: 'active',
    registeredAt: '2024-09-01',
    avatarUrl: null,
  },
  {
    id: 'user-3',
    name: 'Theresa Edwards',
    email: 'theresa@ejemplo.com',
    role: 'student',
    status: 'active',
    registeredAt: '2024-09-05',
    avatarUrl: null,
  },
  {
    id: 'user-4',
    name: 'Marvin McCoy',
    email: 'marvin@ejemplo.com',
    role: 'instructor',
    status: 'active',
    registeredAt: '2024-08-20',
    avatarUrl: null,
  },
  {
    id: 'user-5',
    name: 'Arlene Ross',
    email: 'arlene@ejemplo.com',
    role: 'student',
    status: 'suspended',
    registeredAt: '2024-07-10',
    avatarUrl: null,
  },
  {
    id: 'user-6',
    name: 'Eleanor Pena',
    email: 'eleanor@ejemplo.com',
    role: 'instructor',
    status: 'active',
    registeredAt: '2024-06-15',
    avatarUrl: null,
  },
  {
    id: 'user-7',
    name: 'Robert Fox',
    email: 'robert@ejemplo.com',
    role: 'student',
    status: 'active',
    registeredAt: '2024-10-01',
    avatarUrl: null,
  },
];

export const instructorRequests: InstructorRequest[] = [
  {
    id: 'req-1',
    name: 'Fernando Torres',
    email: 'fernando@ejemplo.com',
    specialty: 'Desarrollo Web',
    experience: '5 años como desarrollador full-stack. Experiencia enseñando en plataformas online.',
    requestDate: '2024-10-10',
    status: 'pending',
  },
  {
    id: 'req-2',
    name: 'Laura Méndez',
    email: 'laura@ejemplo.com',
    specialty: 'Diseño UX/UI',
    experience: '3 años diseñando interfaces. Certificada en Google UX Design.',
    requestDate: '2024-10-12',
    status: 'pending',
  },
  {
    id: 'req-3',
    name: 'Carlos Rivas',
    email: 'carlos.r@ejemplo.com',
    specialty: 'Data Science',
    experience: '4 años en análisis de datos. Maestría en Ciencia de Datos.',
    requestDate: '2024-10-08',
    status: 'pending',
  },
  {
    id: 'req-4',
    name: 'María López',
    email: 'maria.l@ejemplo.com',
    specialty: 'Marketing Digital',
    experience: '6 años en marketing digital. Certificada en Google Ads y Meta Blueprint.',
    requestDate: '2024-09-28',
    status: 'approved',
  },
  {
    id: 'req-5',
    name: 'Pedro Sánchez',
    email: 'pedro@ejemplo.com',
    specialty: 'Fotografía',
    experience: '2 años como fotógrafo profesional.',
    requestDate: '2024-09-25',
    status: 'rejected',
    rejectionReason: 'La experiencia documentada no cumple con el mínimo requerido de 3 años.',
  },
];

export const adminCourses: InstructorCourse[] = [
  {
    id: 'course-1',
    title: 'Introducción a la Programación',
    description: 'Aprende los fundamentos de la programación desde cero.',
    category: 'Programación',
    level: 'Principiante',
    bannerUrl: 'https://images.unsplash.com/photo-1515879218367-8466d910auj2?w=800&h=400&fit=crop',
    status: 'published',
    totalModules: 3,
    totalLessons: 12,
    enrolledCount: 234,
    updatedAt: '2024-10-01',
    modules: [],
  },
  {
    id: 'course-2',
    title: 'Diseño UX/UI con Figma',
    description: 'Domina el diseño de interfaces modernas con Figma.',
    category: 'Diseño',
    level: 'Intermedio',
    bannerUrl: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&h=400&fit=crop',
    status: 'pending_review',
    totalModules: 2,
    totalLessons: 8,
    enrolledCount: 0,
    updatedAt: '2024-10-12',
    modules: [
      {
        id: 'mod-1',
        title: 'Introducción a Figma',
        description: 'Conoce la interfaz y herramientas básicas.',
        order: 1,
        lessons: [
          { id: 'l-1', title: 'Qué es Figma', type: 'video', duration: '10 min', order: 1 },
          { id: 'l-2', title: 'Interfaz de Figma', type: 'text', order: 2 },
          { id: 'l-3', title: 'Herramientas básicas', type: 'video', duration: '15 min', order: 3 },
        ],
      },
      {
        id: 'mod-2',
        title: 'Componentes y Auto Layout',
        description: 'Crea prototipos interactivos.',
        order: 2,
        lessons: [
          { id: 'l-4', title: 'Componentes', type: 'video', duration: '20 min', order: 1 },
          { id: 'l-5', title: 'Auto Layout', type: 'text', order: 2 },
          { id: 'l-6', title: 'Prototipado', type: 'video', duration: '25 min', order: 3 },
        ],
      },
    ],
  },
  {
    id: 'course-3',
    title: 'Marketing Digital Avanzado',
    description: 'Estrategias avanzadas de marketing digital para profesionales.',
    category: 'Marketing',
    level: 'Avanzado',
    bannerUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=400&fit=crop',
    status: 'pending_review',
    totalModules: 4,
    totalLessons: 16,
    enrolledCount: 0,
    updatedAt: '2024-10-11',
    modules: [],
  },
  {
    id: 'course-4',
    title: 'Python para Data Science',
    description: 'Aprende Python aplicado a ciencia de datos.',
    category: 'Programación',
    level: 'Intermedio',
    bannerUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&h=400&fit=crop',
    status: 'rejected',
    totalModules: 3,
    totalLessons: 10,
    enrolledCount: 0,
    updatedAt: '2024-10-05',
    modules: [],
  },
  {
    id: 'course-5',
    title: 'Fotografía Profesional',
    description: 'Técnicas y secretos de la fotografía profesional.',
    category: 'Fotografía',
    level: 'Principiante',
    bannerUrl: 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=800&h=400&fit=crop',
    status: 'draft',
    totalModules: 2,
    totalLessons: 6,
    enrolledCount: 0,
    updatedAt: '2024-10-08',
    modules: [],
  },
];
